// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTugiqbxRszxAj9rTticNQAfNXt97RwD8',
    appId: '1:1032390103474:web:0a3fd5a57d6687cd0694ab',
    messagingSenderId: '1032390103474',
    projectId: 'imagesearchh',
    authDomain: 'imagesearchh.firebaseapp.com',
    storageBucket: 'imagesearchh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mHNruZKbo1EOtyy1kDjcNeU8XjJzrFA',
    appId: '1:1032390103474:android:f509f076bfa281c20694ab',
    messagingSenderId: '1032390103474',
    projectId: 'imagesearchh',
    storageBucket: 'imagesearchh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRHzBgYglAyEFT3wA84-E1LuOMw7zW6w',
    appId: '1:1032390103474:ios:2e871e93a0bec4d30694ab',
    messagingSenderId: '1032390103474',
    projectId: 'imagesearchh',
    storageBucket: 'imagesearchh.appspot.com',
    iosBundleId: 'com.example.searchImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRHzBgYglAyEFT3wA84-E1LuOMw7zW6w',
    appId: '1:1032390103474:ios:2e871e93a0bec4d30694ab',
    messagingSenderId: '1032390103474',
    projectId: 'imagesearchh',
    storageBucket: 'imagesearchh.appspot.com',
    iosBundleId: 'com.example.searchImage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTugiqbxRszxAj9rTticNQAfNXt97RwD8',
    appId: '1:1032390103474:web:94f358ee28291bf60694ab',
    messagingSenderId: '1032390103474',
    projectId: 'imagesearchh',
    authDomain: 'imagesearchh.firebaseapp.com',
    storageBucket: 'imagesearchh.appspot.com',
  );
}
